services:
  database:
    image: alpine:latest
    volumes:
      - ./database:/root/database
    command: tail -f /dev/null # Keep container running

  forum:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./database:/root/database
    environment:
      - DB_PATH=/root/database/forum.db
    restart: always
