// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Session struct {
	ID     []byte
	UserID []byte
}

type User struct {
	ID        []byte
	Email     string
	Username  string
	Password  string
	CreatedAt sql.NullTime
}
