// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Image struct {
	ID        []byte
	CreatedAt sql.NullInt64
	PostID    []byte
}

type Post struct {
	ID        []byte
	Title     string
	Content   string
	CreatedAt sql.NullInt64
	UserID    []byte
}

type Session struct {
	ID        []byte
	CreatedAt sql.NullInt64
	UserID    []byte
}

type User struct {
	ID        []byte
	Email     string
	Username  string
	Password  []byte
	CreatedAt sql.NullInt64
}
