// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id)
VALUES (?, ?)
RETURNING id
`

type CreateSessionParams struct {
	ID     []byte
	UserID []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users ( id, username, password)
VALUES ( ?, ?, ?)
`

type CreateUserParams struct {
	ID       []byte
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Username, arg.Password)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password, created_at FROM users 
WHERE username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
